defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: nervesproject/nerves_system_br:latest
  environment:
    ENV: CI
    MIX_ENV: test
    ELIXIR_VERSION: 1.7.3

install_elixir: &install_elixir
  run:
    name: Install Elixir
    command: |
      wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
      unzip -d /usr/local/elixir Precompiled.zip
      echo 'export PATH=/usr/local/elixir/bin:$PATH' >> $BASH_ENV

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force

install_nerves_bootstrap: &install_nerves_bootstrap
  run:
    name: Install nerves_bootstrap
    command: |
      mix archive.install hex nerves_bootstrap "~> 1.0" --force

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      # Check that compilation works. There aren't any meaningful tests to run
      # SUDO=true -> disable autodetection of a host build and the "helpful"
      # call to sudo
      - run: SUDO=true mix compile
      - run: mix format --check-formatted
      - run: mix docs
      # Comment in when nerves_hub_cli is on hex
      # - run: mix hex.build
